/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Time = IDL.Int;
export const GuestApplication = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Nat,
  'status' : ApplicationStatus,
  'submissionTimestamp' : Time,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'socialHandle' : IDL.Text,
  'personalityAnswers' : IDL.Text,
});
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const ApplicationInput = IDL.Record({
  'age' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'socialHandle' : IDL.Text,
  'personalityAnswers' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllApplications' : IDL.Func([], [IDL.Vec(GuestApplication)], ['query']),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getApplicationById' : IDL.Func([IDL.Text], [GuestApplication], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitApplication' : IDL.Func([ApplicationInput], [IDL.Text], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'updateApplicationStatus' : IDL.Func([IDL.Text, ApplicationStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Time = IDL.Int;
  const GuestApplication = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Nat,
    'status' : ApplicationStatus,
    'submissionTimestamp' : Time,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'socialHandle' : IDL.Text,
    'personalityAnswers' : IDL.Text,
  });
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const ApplicationInput = IDL.Record({
    'age' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'socialHandle' : IDL.Text,
    'personalityAnswers' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllApplications' : IDL.Func([], [IDL.Vec(GuestApplication)], ['query']),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getApplicationById' : IDL.Func([IDL.Text], [GuestApplication], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitApplication' : IDL.Func([ApplicationInput], [IDL.Text], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'updateApplicationStatus' : IDL.Func([IDL.Text, ApplicationStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };